import Link from 'next/link';
import './global.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Learning Next.js',
    template: '%s | Learning Next.js',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2>App Header</h2>
          <nav className='flex gap-2'>
            <Link href="/">Home</Link>
            <Link href="/blog">Blog</Link>
            <Link href="/about">About</Link>
            <Link href="/contact">Contact</Link>
            <Link href="/products">Products</Link>
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
            <Link href="/password">Password</Link>
            <Link href="/dashboard">Dashboard</Link>
          </nav>
          </header>
        <main>{children}</main>
        <footer>App Footer</footer>
      </body>
    </html>
  );
}
