import './global.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Learning Next.js',
    template: '%s | Learning Next.js',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>App Header</header>
        <main>{children}</main>
        <footer>App Footer</footer>
      </body>
    </html>
  );
}
